#!/usr/bin/env python3

# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Chang Liu
# This file is partly generated by ChatGPT. 

import argparse
import os
from collections.abc import Sequence
from lib import fig2, fig3


EXP_CHOICES = (
    "fig2",
    "fig3",
    "fig6",
    "v1",
    "v2",
    "v3",
    "all",
    "v1-poc",
    "v2-poc",
)


def get_supported_cores() -> list[int]:
    """Return the CPU core IDs currently available to this process."""
    # On Linux, this also respects CPU-affinity and container restrictions.
    if hasattr(os, "sched_getaffinity"):
        cores = sorted(os.sched_getaffinity(0))
        if cores:
            return cores

    # Portable fallback: assume CPU IDs are contiguous and start at zero.
    cpu_count = os.cpu_count()
    if cpu_count is None or cpu_count < 1:
        return [0]

    return list(range(cpu_count))


def build_parser(supported_cores: Sequence[int]) -> argparse.ArgumentParser:
    """Create the command-line parser."""
    default_core = max(supported_cores)
    supported_core_set = set(supported_cores)

    def parse_core(value: str) -> int:
        try:
            core = int(value)
        except ValueError as exc:
            raise argparse.ArgumentTypeError(
                f"core must be an integer, but received: {value!r}"
            ) from exc

        if core not in supported_core_set:
            raise argparse.ArgumentTypeError(
                f"unsupported CPU core: {core}; "
                f"available cores: {list(supported_cores)}"
            )

        return core

    parser = argparse.ArgumentParser(
        description="Run an experiment on a selected CPU core.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument(
        "-E",
        "--exp",
        choices=EXP_CHOICES,
        default="all",
        help="experiment to run",
    )

    parser.add_argument(
        "-C",
        "--core",
        type=parse_core,
        default=default_core,
        metavar="CORE_ID",
        help="CPU core ID used to run the experiment",
    )

    return parser


def main():
    supported_cores = get_supported_cores()
    parser = build_parser(supported_cores)
    args = parser.parse_args()

    print(f"Experiment: {args.exp}")
    print(f"CPU core:   {args.core}")

    if args.exp == "fig2":
        fig2.exp(args.core)
        fig2.plot()
    elif args.exp == "fig3":
        fig3.exp(args.core)
        fig3.plot()
    elif args.exp == "all":
        fig2.exp(args.core)
        fig2.plot()
        fig3.exp(args.core)
        fig3.plot()
    else:
        pass

if __name__ == "__main__":
    main()