#!/usr/bin/env bash

# NOTE: This shell code is generated by ChatGPT

set -e

ENV_NAME="pitfall-env"

# 1. Check conda
if ! command -v conda &> /dev/null; then
    echo "❌ Conda is not installed. Please install Miniconda/Miniforge first."
    exit 1
fi

# 2.Initialize conda shell
eval "$(conda shell.bash hook)"

# 3. Check environment
if conda env list | grep -qE "^\s*${ENV_NAME}\s"; then
    echo "✅ Environment '${ENV_NAME}' exists, updating..."
else
    echo "⚠️ Environment '${ENV_NAME}' not found, creating..."
    conda create -n ${ENV_NAME} python=3.11 -y
fi

# 4. Update the environment（environment.yml）
conda env update -n ${ENV_NAME} -f environment.yml --prune

# 5. Build empty data file
mkdir -p data